version: '3.8'
services:
  web:
    build: .
    image: python:3.10-alpine
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             sleep 5 &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn --workers=2 dop3pod.wsgi -b 0.0.0.0:8000"
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      - postgres
    volumes:
      - static:/app/static
    networks:
      - main
    restart: on-failure
  nginx:
    build: ./nginx
    env_file:
      - ./.env
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - web
    networks:
      - main
  postgres:
    image: postgres:14.2-alpine
#    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - main
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    build: ./redis
    image: redis:6.2.6-alpine
    user: root
    ports:
      - "6379:6379"
    networks:
      - main
    volumes:
      - redis:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: on-failure
  celery_worker:
    command: celery -A dop3pod worker -l info
    user: nobody
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    image: python:3.10-alpine
    networks:
      - main
    restart: on-failure

networks:
  main:

volumes:
  pgdata:
  static:
  redis:
