services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             sleep 10 &&
             python manage.py migrate &&
             gunicorn --workers=2 dop3pod.wsgi -b 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - static:/app/static
    networks:
      - main
    restart: on-failure
  postgres:
    image: postgres:14-alpine
#    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - main
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: redis:7-alpine
    user: root
    privileged: true
    command: sh -c "./init.sh"
    networks:
      - main
    volumes:
      - redis:/var/lib/redis:rw
    restart: on-failure
  celery_worker:
    command: celery -A dop3pod worker -l info
    user: nobody
    env_file:
      - .env
    depends_on:
      - web
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    build: .
    networks:
      - main
    restart: on-failure

networks:
  main:

volumes:
  pgdata:
  static:
  redis:
