# Generated by Django 4.0.4 on 2022-04-25 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('genre_id', models.IntegerField(unique=True)),
                ('supergenre', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podcasts.genre')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('artist', models.CharField(max_length=1000)),
                ('pod_id', models.IntegerField(unique=True)),
                ('feed_url', models.CharField(max_length=1000)),
                ('reviews_url', models.CharField(max_length=1000)),
                ('artwork_url', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=50)),
                ('explicit', models.BooleanField(default=False)),
                ('copyright_text', models.CharField(max_length=5000)),
                ('description', models.TextField(max_length=5000)),
                ('discriminate', models.BooleanField(default=False)),
                ('genres', models.ManyToManyField(related_name='genre_genres', to='podcasts.genre')),
                ('primary_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre_primary', to='podcasts.genre')),
            ],
            options={
                'ordering': ['title', 'discriminate'],
            },
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['artist', 'primary_genre'], name='podcasts_po_artist_d927d4_idx'),
        ),
    ]
