# Generated by Django 3.1.2 on 2020-10-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('feed_url', models.CharField(max_length=200)),
                ('artwork_url', models.CharField(max_length=200)),
            ],
            options={'ordering': ['title']}
        ),
    ]
