# Generated by Django 4.1.3 on 2022-11-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_episode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ['-view_count', 'title', 'discriminate']},
        ),
        migrations.AddField(
            model_name='podcast',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
